### ISSUE TITLE
Two tabs open for "Always Open This Site in..."

### ISSUE THREAD

**Issue by morepurplemorebetter** [sagitta1618/temporaryTabContainer#11]
Great add-on for Firefox, especially after the [sad news about Temporary Containers](https://github.com/stoically/temporary-containers/issues/618).

The only issue that I'm having it that when I open a website, that has a default container set, in a new tab (middle-mouse click or ALT+ENTER), two tabs are opened. Both these new tabs are for the same container.

The work-around is to simply not use the middle mouse button or ALT+ENTER, but then the new tab doesn't appear at the end of all the open tabs but next to the current tab. Not a big inconvenience, but figured I would comment here for others to find the workaround (and hope for a fix).

Now off to retrain my muscle memory ;)

**Comment by morepurplemorebetter** [comment]
Adding to this that there are still a couple of scenarios that this results in duplicate tabs that can't be avoided:

1. If the current selected tab is in the same container as the bookmark would open into, then it **is** needed to use CTRL-click (or middle mouse click) to open the bookmark in a new tab. Resulting in the bookmark opening twice if set to "Always open in".
2. When using a shortcut from outside Firefox (e.g. from Explorer) and if the website linked to is set to "Always open in".

Hence, it would be nice if this add-on could check if the site isn't already being opened in a container prior to assigning it a new container.

**Comment by sagitta1618** [comment]
Should be closed by #13 .

**Comment by morepurplemorebetter** [comment]
This looks promising, thanks @dvngn for working on this.

Unfortunately, I just updated to v1.3.0 and the behaviour hasn't changed for me. Two tabs open whenever I open an URL that has been set to "Always open in".

**Comment by dvngn** [comment]
@morepurplemorebetter 

Could you list all of the extensions used in your browser? Thanks.

**Comment by morepurplemorebetter** [comment]
I have just tested this after turning off all my extensions except `tabContainer` and `Multi-Account Containers` and restarting Firefox.

I'm using:
- tabContainer v1.3.0
- Firefox Multi-Account Containers v8.1.3
- Firefox v119.0.1 (64-bit)
- Windows 11 Pro 23H2

&nbsp;

Other extensions I normally have active (but I doubt this is relevant, because the issue persists with these turned off):
- Bitwarden
- Tampermonkey
- DeepL Translate Search Plugin
- uBlock Origin
- Tampermonkey

**Comment by IetIesAai** [comment]
I have 1.3.0, but still seem to have this issue in combination with "always open in" option from multi account containers....

**Comment by morepurplemorebetter** [comment]
This issue is also still appearing for me on v1.3.0.

Sometimes when I open a shortcut it works, but sometimes two tabs still open.
When I Ctrl+Click a link for a site that is set to "always open in", it always opens two tabs.
